### ISSUE TITLE
Improving speed

### ISSUE THREAD

**Issue by albinahlback** [Hummer12007/brightnessctl#102]
I like this package but I find it to be quite slow for its purpose. What can be done to improve the efficiency? More importantly, do you know what is the bottlenecks of the program?

From a user perspective, specifying device, class and quiet mode does not seem to affect the performance that much.

**Comment by xdbob** [comment]
What do you mean by "slow", how do you use `brightnessctl` ?

Since changing the brightness is inherently a privileged operation, we need an escalation mechanism and most distributions should be using the logind's DBus interface witch is slow-ish.

You can try to run `brightnessctl` as `root` to see if its "fast"

**Comment by albinahlback** [comment]
I am not implying that it takes seconds to run, just that it takes more time compared to other solutions I have experienced.

Simple timings via `time` took around 10-20ms (poor benchmark, yes) on my system on Arch Linux with Skylake. In comparison to the very simple [`light`](https://gitlab.com/dpeukert/light), it does feel a lot slower. I haven't benchmarked the latter.

It is understandable that it relies on other stuff that may be bottlenecks, but my question is more if anything actually can be sped up, or that if the current solution does not allow for significant speedups.

**Comment by Hummer12007** [comment]
@albinahlback when not specifying a device, `brightnessctl` still reads all devices even though it then takes only one.

**Comment by Hummer12007** [comment]
@albinahlback
Check out https://github.com/Hummer12007/brightnessctl/pull/103
How does it feel?
From a cursory glance with hyperfine, it should be faster than light (haha) now.

**Comment by albinahlback** [comment]
Yes, that does feel a lot faster! Thanks!

**Comment by Hummer12007** [comment]
Fixed
