### ISSUE TITLE
Didn't detect intel_backlight but nvidia_0

### ISSUE THREAD

**Issue by CyanChanges** [Hummer12007/brightnessctl#110]
I am using `brightnessctl` to change the backlight: 
```shell
$ brightnessctl info
Device 'nvidia_0' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100
```
```
$ brightnessctl set 80
Updated device 'nvidia_0':
Device 'nvidia_0' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100
```
but that didn't work, and I found that there is actually a `intel_backlight` in `/sys/class/backlight`:
```shell
$ ls -l /sys/class/backlight
lrwxrwxrwx root root 0 B Sat Sep 14 13:01:48 2024  intel_backlight ⇒ ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight
lrwxrwxrwx root root 0 B Sat Sep 14 13:01:48 2024  nvidia_0 ⇒ ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/backlight/nvidia_0
```
`intel_backlight` works correctly
```shell
$ echo 120 > /sys/class/intel_backlight/brightness # works
$ brightnessctl --device=intel_backlight set 120 # works too
```
Why it didn't detect the `intel_backlight`?

**Comment by Hummer12007** [comment]
Hi, `info` shows info for a single device. Use `brightnessctl l` to get info for all.

**Comment by CyanChanges** [comment]
> Hi, `info` shows info for a single device. Use `brightnessctl l` to get info for all.

It's the same
![image](https://github.com/user-attachments/assets/e5c53698-e2cb-45b2-95b5-ef88f8c91b98)

**Comment by CyanChanges** [comment]
Hello? @Hummer12007

**Comment by Hummer12007** [comment]
Oh, I see. I'll take a closer look then.

**Comment by Hummer12007** [comment]
Ah, I made a typo. It's `brightnessctl -l` instead. Maybe adding l as an operation makes sense, though it would be inconsistent.

**Comment by deirus16** [comment]
Hi, I have the same issue, my device detect “nvidia_0" as default instead of “intel_backlight” and this is a problem when you try to change the backlight with the key blinds.

```
brightnessctl -l                                                                 
Available devices:
Device 'nvidia_0' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100

Device 'intel_backlight' of class 'backlight':
	Current brightness: 120 (20%)
	Max brightness: 600
```

Is there any way to change this, I would to know why and how to solve it.

**Comment by Hummer12007** [comment]
specify `-d intel_backlight` as an argument in keybinds
