### ISSUE TITLE
Dimming the display turns it completely blank

### ISSUE THREAD

**Issue by arbitrary-dev** [Hummer12007/brightnessctl#125]
Applying `brightnessctl s 5%-` multiple times turns my display completely blank/black, even though documentation states that "minimum brightness when using delta values, defaults to 1".

Adding `-n1` fixes the issue though.

**Comment by andeston** [comment]
I think this is a docs issue. `0` is definitely the minimum. I can't think of any reason why `1` should be the default. On my setup, the display is still on and visible at `0` brightness. That behavior seems to be system dependent.

I don't have any access to this repo and it appears to be abandoned, see #124. I made a PR, but it likely will never be merged. I merged 5c4582b0fc2fa8d647937324067ed1d52badbbdc in the [`develop` branch](https://github.com/andeston/brightnessctl/tree/develop) of my fork.

**Comment by Hummer12007** [comment]
If you invoke it as `brightnessctl s 5%- -n` or `brightnessctl --min-value s 5%-`, minimum brightness is indeed limited to 1. But yeah, docs should mentioned it more clearly (is limited to 1 when provided or smth). Argument handling with shorthand optional arguments is indeed wonky and I need to fix it.
