### ISSUE TITLE
the temporary directory should use `$XDG_RUNTIME_DIR`

### ISSUE THREAD

**Issue by CameronNemo** [Hummer12007/brightnessctl#22]
Documentation: http://man7.org/linux/man-pages/man3/mkdtemp.3.html

**Comment by Hummer12007** [comment]
I'd like you to elaborate.
Which temporary directory are you referring to?

**Comment by CameronNemo** [comment]
https://github.com/Hummer12007/brightnessctl/blob/master/brightnessctl.c#L19

**Comment by Hummer12007** [comment]
And why do you think it should be unpredictable?
And in addition, please remember, that the temporary directory must be persistent in between runs.

**Comment by CameronNemo** [comment]
> temporary directory must be persistent in between runs

I was unaware of this. Can you use `$XDG_RUNTIME_DIR`? Safer than `/tmp`, where permissions are more relaxed.

**Comment by Hummer12007** [comment]
Yeah, I thought that using XDG_RUNTIME_DIR makes some sense while writing the previous, though for reasons unrelated to security.
