### ISSUE TITLE
Allow only physically connected users to use brightnessctl

### ISSUE THREAD

**Issue by xdbob** [Hummer12007/brightnessctl#23]
It would be great and doable. It would require a daemon, let's call it `brightnessd` running in root (or whatever user allowed to access the device) listening on DBus and allowing a commands **only** if the user have an active session connected to a seat.

I am not sure how we could somehow attach the backlight to a *specific* seat, so it would at first probably allow any user connected to any seat.

What do you think ?

I am open to try and create the needed changes.

Note: [logind documentation](https://www.freedesktop.org/wiki/Software/systemd/logind/)
It would also probably require systemd

**Comment by SirCmpwn** [comment]
>It would be great

Why?

**Comment by xdbob** [comment]
In the case where I share my laptop with my friends both physically and over SSH. It is a nonsense to allow a user remotly control the the brightness since he probably doesn't even have the necessary permissions to output something to the screen.

My goal is to have a dynamic permission system a bit like with the `uaccess` tag of udev/systemd.

And since `DBus` is highly configurable, we could have users that *always* have access to the backlight (root for example).

**Comment by SirCmpwn** [comment]
But that'd require depending on dbus, yuck

**Comment by Hummer12007** [comment]
@xdbob I'm sure you can mess around with polkit to achieve this.

**Comment by CameronNemo** [comment]
I have a polkit policy for something like this. I wrote it for [light](https://github.com/CameronNemo/light/blob/master/contrib/light.policy.in) though. See the `annotate key` field for where the binary path goes.
