### ISSUE TITLE
INSTALL_UDEV_RULES not consistent with README

### ISSUE THREAD

**Issue by AJGQ** [Hummer12007/brightnessctl#28]
In the README file you say that INSTALL_UDEV_RULES by default is 0 and 1 is to install the udev rules, but in the Makefile the default value is actually 1 and 0 is to install the udev rules. A small thing but bugged when I was changing it to 1 :) .

**Comment by Hummer12007** [comment]
Thanks. I'd welcome a PR with the fix (or I can do it myself in a few days).

**Comment by Hummer12007** [comment]
To clarify; it's the README which should be fixed.
