### ISSUE TITLE
Simple frontend for brightnessctl

### ISSUE THREAD

**Issue by Cuperino** [Hummer12007/brightnessctl#29]
Thank you for writing `brightnessctl`. It's fills a gap `xbacklight` left with issues that haven't been addressed in a while.

This isn't really an issue, but I didn't know where else to write. I wrote a simple frontend for `brightnessctl` in Python 3, called `simplebrightness`. It's very basic but it solves the need for those who want a simple frontend. I plan on adding the ability to switch across displays, and maybe switch between preferred intensities, in future updates. All while keeping it simple, as the name goes.

You can find the frontend at:
https://github.com/javiercordero/simple-brightness

**Comment by Hummer12007** [comment]
Wow, that's really cool. Nice job!

**Comment by javiercordero** [comment]
Thank you! I'll keep you posted of future updates.
