### ISSUE TITLE
Packages for Fedora 30 

### ISSUE THREAD

**Issue by FloThinksPi** [Hummer12007/brightnessctl#31]
Could you build and upload Packages for Fedora 30, as it is now released ?
Up until now, the packages are only available on Fedora 28 and 29.

Best 
Florian

**Comment by Hummer12007** [comment]
If I remember correctly, @Fale maintained the package, though it seems to be orphaned now.

**Comment by jelford** [comment]
I'd be willing to take on brightnessctl for Fedora. I haven't done any Fedora packaging before so I imagine it will take me a little bit to get set up. Is there anything you'd like me to do for that? Looking at the addition of Alpine, I think I should just send you a PR with a link when it's ready?

**Comment by jelford** [comment]
In the meantime, I have set up a copr repo for this: [here](https://copr.fedorainfracloud.org/coprs/jelford/brightnessctl/)

>  I remember correctly, @Fale maintained the package, though it seems to be orphaned now

It looks like you're correct, but he stopped maintaining it in 2017 ([here](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/TTRKFTADCEHAJSZ55YXIPT3DOZY5RTYW/)) and the package became orphaned.

**Comment by jelford** [comment]
Just to provide a bit of an update on this for anyone who's interested:
* The version in my copr repo [here](https://copr.fedorainfracloud.org/coprs/jelford/brightnessctl/) is tracking v0.4 (the latest tagged release). It uses the `setuid` binary method. I have been running it locally without issues for some weeks now.
* I have opened a request to include the package into Fedora [here](https://bugzilla.redhat.com/show_bug.cgi?id=1778512).
  * This is blocked on me getting "sponsored" as a packager. The reviewer has reached out to me on that, so it's blocked on my finding time to progress (expect progress to be slow from my side - sorry).
* Once https://github.com/Hummer12007/brightnessctl/issues/40 is closed off I will bump the version in the copr build. Expect a further delay for me to get the "real" fedora package updated; I want to finish the process with the v0.4 review before complicated matters by updating what I've asked someone to review.

**Comment by jelford** [comment]
Looks like I was beaten to the punch; @gicmo has put together a package [here](https://src.fedoraproject.org/rpms/brightnessctl). I expect this to be included in F32. I've also sent a PR to get the version bumped to 0.5.1.

The copr repo will remain active for the time being (I'm running out of it on F31), but it probably won't have the stability expectations you'd expect from official packages.
