### ISSUE TITLE
Fix memory "leaks"

### ISSUE THREAD

**Issue by xdbob** [Hummer12007/brightnessctl#34]
A lot of the allocated memory isn't freed, I don't think it's an issue in itself since the program is short lived but it would make tools like `valgrind` or `ASAN` happy and thus make potential bugs easier to debug.

**Comment by Hummer12007** [comment]
I chose not to when I first wrote the program. You can just run with ASAN_OPTIONS=detect_leaks=0 or something similar.

**Comment by xdbob** [comment]
Fine by me
