### ISSUE TITLE
Doesn't detect external monitors

### ISSUE THREAD

**Issue by kujaw** [Hummer12007/brightnessctl#38]
Ubuntu 18.04.
I have one laptop and two external monitors connected.
```
$ xrandr -q | grep " connected"  
eDP-1 connected (normal left inverted right x axis y axis)  
DP-1-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm  
DP-1-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
```
However, brightnessctl doesn't detect them.
```
$ brightnessctl -l
Available devices:
Device 'intel_backlight' of class 'backlight':
	Current brightness: 24000 (20%)
	Max brightness: 120000

Device 'input4::capslock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'phy0-led' of class 'leds':
	Current brightness: 1 (100%)
	Max brightness: 1

Device 'input4::scrolllock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'input4::numlock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'dell::kbd_backlight' of class 'leds':
	Current brightness: 1 (50%)
	Max brightness: 2
```

**Comment by kujaw** [comment]
I've just read deeper that the tool does not manage external monitor brightness by design. So this issue is not a bug, rather may be treated as an feature request.

**Comment by Hummer12007** [comment]
You can use ddcutil for that. I will keep this open for now.

**Comment by kennylevinsen** [comment]
The right thing to do is just to support multiple devices in /sys/class/backlight. A user can then install ddcci-driver-linux (currently an out-of-tree module), which through the ddcci-backlight module provides backlight interfaces for external displays that work exactly like intel_backlight.

(Well, they're slower than intel_backlight, but *much* faster than the userspace tools.)

**Comment by Hummer12007** [comment]
It works already

**Comment by almir-campos** [comment]
@kennylevinsen 
I just would to understand a little bit more why you said "_WIth multiple device support, there's nothing for brightnessctl to do_", if it is possible for you.

Until I read your sentence I thought it would be quite reasonable to use the same program (in this case `brightnessctl`) to control the brightness of multiple monitors. But now I'm wondering if I'm missing something.

I read that you also said that "_The right thing to do is just to support multiple devices in /sys/class/backlight._". Is that the case of `xrandr`, for example? Even if it is, it seems the backlight thing seems to be transparent to the user - we just run `xrandr ... --brightness ... ` and that's it.

Could you clarify, please?

Thank you.

**Comment by Hummer12007** [comment]
*there's nothing for brightnessctl to do* implies that if the system has ddci-driver-linux installed, the monitors will be exposed in `/sys/class/backlight`, and thus brightnessctl will be able to deal with them without any changes.

**Comment by Hummer12007** [comment]
I might not be against a PR which would add direct DDCI (or w/e it's called) support.

**Comment by sbrl** [comment]
> we just run `xrandr ... --brightness ...` and that's it.

....except if you are on Wayland.
