### ISSUE TITLE
Bump version to 0.5 and release on github

### ISSUE THREAD

**Issue by jelford** [Hummer12007/brightnessctl#40]
Hi,

I've been using `brightnessctl` with systemd integration enabled for a little while, and everything seems to work okay.

I'd like to pick up packaging this for Fedora 31 (as mentioned on #31 ), but ideally would prefer for that package to make use of the new systemd integration, rather than setuid or udev rules. Since it seems that people prefer to have packages built against "released" versions of upstream, would it be okay to bump the version and cut a new release?

**Comment by Hummer12007** [comment]
Ok, I'll try my hardest to do this by the end of the week. I need to integrate one bugfix I made on my local branch.

**Comment by jelford** [comment]
Thanks, much appreciated. No sweat if you don't get to it; I probably won't
have another chance to look at this during the week anyway, and for now I'm
happy running out of my copr repo. Besides, I've not been through the
Fedora review process before so that might take some time anyway.

**Comment by gdamjan** [comment]
polite nudge :)

**Comment by Hummer12007** [comment]
* nudge acknowledged, starts working

**Comment by Hummer12007** [comment]
Please test the master branch for a while, if no issues are found, I'll tag a new release tomorrow.

**Comment by jelford** [comment]
Thanks for coming back to this @Hummer12007 ! I think we have a couple of little issues with the commits pushed up on the 25th & 26th of Jan; I get a couple of build errors locally. I've opened up #44 to address (it also includes a tweak to the install in case systemd is in use).

**Comment by Hummer12007** [comment]
Done!

**Comment by jelford** [comment]
Great, thanks!
