### ISSUE TITLE
Specify settings ( keyboard leds ) 

### ISSUE THREAD

**Issue by wantedrbk** [Hummer12007/brightnessctl#47]
It works but i want to ask can i change colors of my keyboard ( now its wave mode ), only able to change brightness level ? , maybe i can change something else 
![leds](https://user-images.githubusercontent.com/55120646/78589744-44db0d00-7873-11ea-9ca4-2ad5ccbd24e5.png)

**Comment by Hummer12007** [comment]
You need to use something like https://github.com/wroberts/rogauracore to control your keyboard colors.
