### ISSUE TITLE
Support for getting device brightness as a percentage

### ISSUE THREAD

**Issue by rgcv** [Hummer12007/brightnessctl#55]
Instead of just obtaining the absolute value, maybe it would be nice to extend this and make it possible to obtain a percentage value as well.

I've look around the code, and it seems the easiest way to support this would be to add another operation, say `GET_PERCENTAGE` in the form of `g%` which could look something like the following:

```sh
$ brightnessctl
Device 'mock_device' of class 'mock_class':
        Current brightness: 127 (50%)
        Max brightness: 255
$ brightnessctl -d mock_device g
127
$ brightnessctl -d mock_device g%
50
```

I can probably submit a PR and have this working exactly like this.  Alternatively, it doesn't have to be `g%` as that would "mess up" operation matching with an extra if for `g`.  Could be `p` (for "`p`ercentage"), for instance.

Otherwise, looking into extending `g` itself is also relatively messy and would require more moving parts.  In fact, it would look more like `s` (`SET`) then, which I find relatively unnecessary.

I'd like to discuss this further.  In the meantime, I can test something out using `p` as the operation, defining `GET_PERCENTAGE` or `GET_PERCENT` as another operation type, and submit a PR.

**Comment by rgcv** [comment]
As an addendum, the obvious (yet not as pretty) alternative workaround without changing `brightnessctl` is parsing the machine output (csv) and eliminating the percent value.  An example using `awk` and `tr` in shell:

```sh
$ brightnessctl -d mock_device g | awk '{print $4}' | tr -d %
50
```

**Comment by MisterDA** [comment]
> As an addendum, the obvious (yet not as pretty) alternative workaround without changing `brightnessctl` is parsing the machine output (csv) and eliminating the percent value. Here's an example using `awk` and `tr` in shell:
> 
> ```shell
> $ brightnessctl -d mock_device g | awk -F, '{print $4}' | tr -d %
> 50
> ```

Your command misses the `-m` flag for outputting CSV, and the `g` option must be removed (it may be that the interface has changed). Here’s an updated version to extract the persentage:

```shell
brightnessctl -m -d mock_device | awk -F, '{print substr($4, 0, length($4)-1)}'
```
