### ISSUE TITLE
default minimum value

### ISSUE THREAD

**Issue by ghost** [Hummer12007/brightnessctl#62]
Do you think setting default minimum value to `1` is a good idea?

**Comment by tamerfrombk** [comment]
> Do you think setting default minimum value to `1` is a good idea?

Just curious, why do you think it isn't a good idea and what should the minimum value be?

**Comment by frogtile** [comment]
I think setting default minimum value to `1%` is better.

**Comment by Hummer12007** [comment]
On a lot of devices, 0 is perfectly usable (while on some it's not). Closing as it depends on the device.
