### ISSUE TITLE
`--quiet` does not suppress output when called with `--restore`

### ISSUE THREAD

**Issue by jonasc** [Hummer12007/brightnessctl#65]
```
$ brightnessctl --version
0.5
```
but the package is supposed to be 0.5.1 (https://archlinux.org/packages/community/x86_64/brightnessctl/).

Command: `brightnessctl --restore --quiet` (After having saved the previous value)
Expected output: No output at all
Actual output:
```
Device 'intel_backlight' of class 'backlight':
	Current brightness: 2220 (50%)
	Max brightness: 4438
```

**Comment by jonasc** [comment]
I tested it now with the latest code from the repository and it works. So I'm closing this now. Sorry for the noise.

**Comment by eternal-sorrow** [comment]
There was no release that contains that code though

**Comment by sheepymeh** [comment]
I just tested this with the latest version from Arch Linux (0.5.1) and the AUR version that builds from git, but both still exhibit the same incorrect behavior
