### ISSUE TITLE
[PATCH] Add elogind support

### ISSUE THREAD

**Issue by abcdw** [Hummer12007/brightnessctl#67]
```patch
From e00637efaeb5c8b429b40fd45dd4598544df871a Mon Sep 17 00:00:00 2001
From: Andrew Tropin <andrew@trop.in>
Date: Tue, 25 May 2021 11:08:10 +0300
Subject: [PATCH] Add elogind support

<systemd/sd-bus.h> can be provided not only by libsystemd, but also by
libelogind, so lookup for libelogind too.

---
Probably it's also a reasonable idea to rename ENABLE_SYSTEMD to
ENABLE_LOGIND

 Makefile | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/Makefile b/Makefile
index 105f5d6..82b8595 100644
--- a/Makefile
+++ b/Makefile
@@ -18,6 +18,8 @@ MODE = ${MODE_${INSTALL_UDEV_RULES}}
 ifdef ENABLE_SYSTEMD
 	CFLAGS += ${shell pkg-config --cflags libsystemd}
 	LDLIBS += ${shell pkg-config --libs libsystemd}
+	CFLAGS += ${shell pkg-config --cflags libelogind}
+	LDLIBS += ${shell pkg-config --libs libelogind}
 	CPPFLAGS += -DENABLE_SYSTEMD
 	INSTALL_UDEV_RULES=0
 	MODE = 0755
-- 
2.31.1
```

**Comment by Hummer12007** [comment]
><systemd/sd-bus.h> can be provided not only by libsystemd, but also by libelogind, so lookup for libelogind too.

Adding https://github.com/emersion/basu as well (another sd-bus provider) support would be helpful.

>Probably it's also a reasonable idea to rename ENABLE_SYSTEMD to ENABLE_LOGIND

Yes, it is.

We probably need a switch to explicitely specify the implementation of sd-bus, if necessary.

**Comment by xdbob** [comment]
I suggest to create a configure script generating a `config.mk`  that would handle the build-time configuration, IMHO the build configuration is already more painful than it should be without handling 3 dbus providers.

If needed I can work on it and submit a patch soon-ish

**Comment by abcdw** [comment]
On 2021-09-09 10:47, Antoine DAMHET wrote:

> I suggest to create a configure script generating a `config.mk`  that would handle the build-time configuration, IMHO the build configuration is already more painful than it should be without handling 3 dbus providers.
>
> If needed I can work on it and submit a patch soon-ish

Thanks a lot for implementing it!

-- 
Best regards,
Andrew Tropin
