### ISSUE TITLE
Feature request: Configure brightness of external monitors

### ISSUE THREAD

**Issue by Armoken** [Hummer12007/brightnessctl#76]
At this moment brightnessctl can't see and manipulate with external monitors. It's would be awesome if brightnessctl will have support of configuring external monitors using DDC/CI (Display Data Channel Command Interface). Now I can do it with the help of ddcutil utility.
[Example of ddcutil usage](https://wiki.archlinux.org/title/backlight#Switch_off_the_backlight)

What do you think about it?
If you have nothing against it, I can tried to implement it.

**Comment by Hummer12007** [comment]
https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux is the better way, exposing everything we need via the backlight sysfs interface that brightnessctl uses.

**Comment by anishmittal2020** [comment]
@Hummer12007 I installed [Ubuntu – Details of package ddcci-dkms in focal](https://packages.ubuntu.com/focal/ddcci-dkms) `sudo apt install ddcci-dkms`, and restarted. I am trying to set the brightness of my external monitor connected with HDMI cable to 50%

```bash
$ xrandr -q | grep " connected"
eDP-1-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
HDMI-1-1 connected primary 1920x1200+1920+0 (normal left inverted right x axis y axis) 519mm x 324mm

$ brightnessctl -d=hdmi* s 50
Device '=hdmi*' not found.
```

Any suggestions?

**Comment by Hummer12007** [comment]
It's `-d ath9k-phy0` instead

**Comment by anishmittal2020** [comment]
@Hummer12007 This device is for Wireless. As, I said before the external monitor is not even listed in the list of devices!
