### ISSUE TITLE
set brightness on AMD APU pip vs apt

### ISSUE THREAD

**Issue by Meresmata** [Hummer12007/brightnessctl#78]
I first installed brightnessctl via apt.
But then I could not set the brightness via `brightnessctl s +10%`. Although brightness-udev (0.5.1-2) is installed.
I than I uninstalled brightnessctl and installed via pip.
When calling brightnessctl now I get an error, that there is no path: `/sys/class/backlight/intel_backlight/actual_brightness` which is correct because the laptop uses a AMD APU with the path `/sys/class/backlichtamdgpu_bl0`

How do can I set the brightness, on the system?

**Comment by Hummer12007** [comment]
`brightnessctl` from pip is not related to this project.
