### ISSUE TITLE
Need Help: max brighness at 10%

### ISSUE THREAD

**Issue by coffebar** [Hummer12007/brightnessctl#83]
I believe it's not a problem of  brightnessctl, but maybe you can help.

```
➜  ~ brightnessctl s 1
Updated device 'nvidia_0':
Device 'nvidia_0' of class 'backlight':
	Current brightness: 1 (1%)
	Max brightness: 100
```
at 1% - real screen brightness is looks like 10%
```
➜  ~ brightnessctl s 10
Updated device 'nvidia_0':
Device 'nvidia_0' of class 'backlight':
	Current brightness: 10 (10%)
	Max brightness: 100
```
at 10% - real screen brightness is looks like 100%
```
➜  ~ brightnessctl s 100
Updated device 'nvidia_0':
Device 'nvidia_0' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100
```
at 100%- real screen brightness is looks like 50%

for example "11" looks darker then "1".

Device is a Thinkpad with Nvidia graphics. 

/sys/class/backlight/nvidia_0/actual_brightness is changing as expected 

Any ideas?

**Comment by shashankk90** [comment]
This issue may be related to nvidia drivers and not brightnessctl.
Check https://bbs.archlinux.org/viewtopic.php?pid=2072664
