### ISSUE TITLE
Working vs not working(?!)

### ISSUE THREAD

**Issue by ArchieLinux** [Hummer12007/brightnessctl#85]
Greetings! `brightnessctl` has shown itself to be the instant solution to regaining control over my native monitor's brightness [via dimmer key (F1) and brighter key (F2)] on my 2019 iMac desktop. I access it easily through keybindings I added within my wmi3 config file.

PROBLEM:  I cannot get my 2011 MacBookPro to respond at all ... nor can I get my Dell OptiPlex 7200 to respond ... yet all three are running identical setups, i.e., the same Zen kernel 6.1.6, EndeavourOS, i3, etc. 

The difference I detect is that the device '`acpi_video0`' is listed via `brightnessctl -l` on the iMac but there is nothing comparable on the other two platforms (other led devices but not a monitor). In short, I can't seem to find the monitor(s) in the device listings as shown by `brightnessctl`. 

Any thoughts on why? ...  and how I might get `brightnessctl` to recognize the monitor device equivalents on the others?

**Comment by Hummer12007** [comment]
External monitors should work with the DDCI module, but in practice it doesn't work (see #105).
